### ISSUE TITLE
Mongoose forcing update and type error

### ISSUE THREAD

**Issue by mateusbarros92** [ExtraBB/typegoose-cursor-pagination#19]
Mongoose is forcing me to update its version (See the screenshot)

![Screenshot from 2021-01-07 09-07-34](https://user-images.githubusercontent.com/28282371/103891014-d6f49800-50c7-11eb-8ae5-5f25b6843d8d.png)

I updated the mongoose version and i had a type error with this lib 

![Screenshot from 2021-01-07 09-09-53](https://user-images.githubusercontent.com/28282371/103891172-20dd7e00-50c8-11eb-877b-c4de44dbdcac.png)

![Screenshot from 2021-01-07 09-11-09](https://user-images.githubusercontent.com/28282371/103891266-51251c80-50c8-11eb-9c72-2fe5b976a9ca.png)

This error don't extends mongoose types and show me errors when i try to use mongoose functions

Can you fix it?

**Comment by ExtraBB** [comment]
It looks like you updated `typegoose` to a higher version, for which you needed to upgrade `mongoose` as well. (https://typegoose.github.io/typegoose/docs/guides/error-warnings-details#mongoose-version-e001)

The easiest solution would be to downgrade `typegoose` back to the version that comes with this package. This should fix the type issues that you're having.

If you really need the higher `typegoose` version, you can try to fix the issues and submit a pull request with the fixes and dependency upgrades.
