### ISSUE TITLE
Nestjs-typegoose Support

### ISSUE THREAD

**Issue by Lishenga** [ExtraBB/typegoose-cursor-pagination#20]
Hey, could you by any chance allow or start supporting typegoose inside Nest Js Framework using the Nest Js Framework typegoose library called nestjs-typegoose?

**Comment by ExtraBB** [comment]
Hi, I'm not sure if that's possible without forking this project. I've never used NestJS before. You can fork this project and give it a try. I'd be happy to help out if you get stuck.

**Comment by Lishenga** [comment]
okay thank you, i will notify you of any issues
