### ISSUE TITLE
This redundant 'await' on a non-promise

### ISSUE THREAD

**Issue by truongleeuet** [ExtraBB/typegoose-cursor-pagination#29]
I have issues when using findPage method. I checked the code and find the problem in lib: 
```
export interface IPaginateModel<T> extends Model<DocumentType<T>, {}> {
    findPaged(options: IPaginateOptions, query?: Object, projection?: Object, _populate?: (Object | string)[]): DocumentQuery<IPaginateResult<DocumentType<T>>, DocumentType<T>>;
}
```
But implement code return Promise:
`async function findPaged<T>(options: IPaginateOptions, _query?: Object, _projection?: Object, _populate?: ModelPopulateOptions | ModelPopulateOptions[]): Promise<IPaginateResult<T>>{...}`.
Please help me confirm this. Thank you.

**Comment by ExtraBB** [comment]
Thank you, I updated this in v2.0.3
