### ISSUE TITLE
Examples seem to be outdated

### ISSUE THREAD

**Issue by hasezoey** [ExtraBB/typegoose-cursor-pagination#31]
Currently the examples seem to be outdated, at least in the aspect of still showing usage of `typegoose` with `extends Typegoose`, but this package is already using `@typegoose/typegoose` as a dependency

**Comment by ExtraBB** [comment]
Yes you're right, I can probably look at it next weekend. If you know how to, also feel free to send a PR to update them.

**Comment by hasezoey** [comment]
> If you know how to, also feel free to send a PR to update them.

i am not really familiar with this project or what it requires to be updated, but i may try to do it for https://github.com/typegoose/typegoose/issues/734

**Comment by ExtraBB** [comment]
Readme is updated
