### ISSUE TITLE
Error with limit when sortField is defined

### ISSUE THREAD

**Issue by agostinhodev** [ExtraBB/typegoose-cursor-pagination#32]
**Description:** If the collection has 10 documents and the client sends at request `limit:10`, the lib will return all 10 documents as expected. 

![image](https://user-images.githubusercontent.com/45676811/180874273-291942d4-b05b-4e82-aa66-c2d528335fcc.png)

However, if the limit is set below the total of documents, say `limit:2`, the lib throws the following error:
![image](https://user-images.githubusercontent.com/45676811/180874394-8c0da3a7-db54-4719-b69d-e56796467546.png)

Full Error:
```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'path')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getPaginatedOrders"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'path')",
            "    at prepareCursor (/home/USERNAME/Documents/MY-PROJECT/v1/MY-PROJECT-back-end-2020/.webpack/service/src/webpack:/node_modules/typegoose-cursor-pagination/lib/response.js:68:1)",
            "    at prepareResponse (/home/USERNAME/Documents/MY-PROJECT/v1/MY-PROJECT-back-end-2020/.webpack/service/src/webpack:/node_modules/typegoose-cursor-pagination/lib/response.js:49:1)",
            "    at Function.<anonymous> (/home/USERNAME/Documents/MY-PROJECT/v1/MY-PROJECT-back-end-2020/.webpack/service/src/webpack:/node_modules/typegoose-cursor-pagination/lib/index.js:58:1)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/USERNAME/Documents/MY-PROJECT/v1/MY-PROJECT-back-end-2020/.webpack/service/src/webpack:/node_modules/typegoose-cursor-pagination/lib/index.js:19:42)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

it occurs when the `sortField` is setted. In this case: 
```javascript
const orders: any = await OrderModel.findPaged(
     { ...paginateOptions, sortField: "createdAt", sortAscending: false },
     query,
     {}
);
```

## Possible solutions
The file located at `node_modules/typegoose-cursor-pagination/lib/response.js:65` has a function called `prepareCursor` wich receives two args: `doc` and `sortField`. It was replaced as the following code: 

```javascript
function prepareCursor(doc, sortField) {
    // Always save _id for secondary sorting.
    if (sortField && sortField !== "_id") {
        return bsonUrlEncoding.encode([doc.sortField]);
    }
    else {
        return bsonUrlEncoding.encode([doc._id]);
    }
}
```
After that, it works here, however it's necessary that you validate if it is the correct soluction and behavior!

**Expected Behavior:** Return the correct pagination when limit is not equal to the total of documents

Tks!

**Comment by ExtraBB** [comment]
Hi! Thanks for raising the issue. The code that you removed in your proposed solution was added here to support nested paths: https://github.com/ExtraBB/typegoose-cursor-pagination/pull/14. I think it would be worthwhile to keep this functionality. If you can make a solution that keeps this functionality, please make a PR. I don't know when I'll have time to look into it myself.

**Comment by ExtraBB** [comment]
I replaced `ramda` with `object-path`. This should be fixed.
